apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeploy_conv_peso
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: conv_peso
template:
  metadata:
        labels:
          app: conv_peso
        spec:
          containers:
             - name: conv_peso
               image: rafaelsucra/conversao-peso
               ports:
                 - containerPort:8080
---
apiVersion: v1
kind: Service
metadata:
   name: conv_peso
spec:
   selector:
      app: conv_peso
   ports:				
      - port 8080
        protocol: TCP
        name: http
        type: ClusterIP

